name: Docker tests

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: [self-hosted,"${{ matrix.os }}"]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: docker-tests/build-docker-images.sh
    - name: Run the Docker tests
      run: docker-tests/run-docker-tests.sh userspace
